### ISSUE TITLE
Use elements sass module

### ISSUE THREAD

**Issue by easternbloc** [UKHomeOffice/passports-frontend-toolkit#34]
If this is actioned it would be super nice to move away from a copied set of elements SASS.

https://github.com/alphagov/govuk_elements/issues/155

**Comment by easternbloc** [comment]
This is a thing now. https://www.npmjs.com/package/govuk-elements-sass we should totally use this.

**Comment by gavboulton** [comment]
I agree.

**Comment by daniel-ac-martin** [comment]
It's got sass in the name but it looks like it has some useful javascript in it too. Can we expose that?

Elements also relies on govuk-frontend-toolkit, do we care? Should we pin to the same version? Can we eliminate our dependency on it and use it through govuk-elements-sass?

**Comment by daniel-ac-martin** [comment]
Ignore me; it is just sass files.
I missed the .npmignore file.

**Comment by daniel-ac-martin** [comment]
BTW, we should probably start using .npmignore in out modules. Could save people from downloading the tests and maybe some other stuff.

**Comment by daniel-ac-martin** [comment]
After further investigation, I'm not sure why govuk-elements-sass depends on govuk_frontend_toolkit as it seems it is left up the to developer to import it prior to elements anyway.

**Comment by daniel-ac-martin** [comment]
Closing this as it has now been done.
